postprocessor:
  name: ants
  APS_mode: True  # search for the best.
  postprocessor_args:
    eta: 0.5
    group_num: 100
    random_permute: True
    in_score: sum
    neglabel_init_flag: False
    ens_stop_step: 20
    mllm_model_type: QWEN