dataset:
  name: cifar100
  num_classes: 100
  pre_size: 224
  image_size: 224

  interpolation: bicubic # following clip.
  normalization_type: clip ## following clip.  cifar norm, 43.9 clip zero shot acc.

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/train_cifar100.txt
    few_shot: 2
    batch_size: 128
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/val_cifar100.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/test_cifar100_full.txt
    batch_size: 200
    shuffle: False

ood_dataset:
  name: cifar100_ood
  num_classes: 100
  
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/val_tin.txt
  nearood:
    datasets: [cifar10, tin]
    cifar10:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_cifar10.txt
    tin:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_tin.txt
  farood:
    datasets: [mnist, svhn, texture, places365]
    mnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_mnist.txt
    svhn:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_svhn.txt
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_texture.txt
    places365:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_places365.txt
